#!/bin/bash

#
# Unit test for twmail_hooks
#

# Data locations
DIRNAME=$(cd $(dirname $0);pwd)
DATA_DIR=$(mktemp -dt $(basename $0))
export TASKRC=$(mktemp -t taskrc)

source $DIRNAME/../helpers/assertions

# Create custom taskrc
cat > $TASKRC <<HERE
data.location=$DATA_DIR
json.array=on
verbose=off
HERE

# Canonical path to test_hook
export TWMAIL_HOOK=$DIRNAME/../helpers/test_hook

# Create new task using mail fixture
cat $DIRNAME/../fixtures/mail01.txt | $DIRNAME/../../bin/twmail_hooks

# Read back and run assertions
SUBJECT=$(task export | ruby -r json -e "puts JSON[ARGF.read].first['description']")

assert_equal "Send some test mails" "$SUBJECT"

# Clean up
rm -Rf $DATA_DIR
rm -Rf $TASKRC
